import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Background from "@/components/background";
import { Navbar } from "@/components/layout/navbar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Background>
          <Navbar
            navItems={[
              { title: "Home", href: "/" },
              { title: "About", href: "/about" },
              { title: "Contact", href: "/contact" },
              { title: "Games", href: "/games" },
              { title: "Editor", href: "/editor" },
              { title: "Market Place", href: "/marketplace" },
              { title: "Community", href: "/community" },
            ]}
          />
          {children}
          <Toaster />
        </Background>
      </body>
    </html>
  );
}
