export const MAX_SEARCH_RESULTS = 50;
export const VERSION_ID_RANDOM_START = 2;
export const VERSION_ID_RANDOM_END = 9;
export const VERSION_ID_RANDOM_LENGTH = 36;
export const VARIATIONS_COUNT = 3;
export const PROMPT_READY_THRESHOLD = 100;
export const DEBOUNCE_DELAY = 300; // milliseconds
export const MAX_FEATURES_DISPLAY = 3;
export const IDEATION_TEMPERATURE = 0.8;
export const GAME_IDEA_FEATURES_DISPLAY_LIMIT = 5;
export const PAGE_SIZE = 12;
export const WALLET_ADDRESS_PREFIX_LENGTH = 6;
export const WALLET_ADDRESS_SUFFIX_LENGTH = 4;
export const MAX_TAGS_DISPLAY = 3;
